from enum import Enum


class ResponseStage(str, Enum):
    CV_SELECTED = "CV_SELECTED"
    CV_SENT = "CV_SENT"
    DETAILS_CLARIFICATION = "DETAILS_CLARIFICATION"
    CLIENT_REVIEW = "CLIENT_REVIEW"
    PRECHECK = "PRECHECK"
    INTERVIEW_1 = "INTERVIEW_1"
    INTERVIEW_2 = "INTERVIEW_2"
    INTERVIEW_3 = "INTERVIEW_3"
    WAIT_DECISION = "WAIT_DECISION"
    ON_PROJECT = "ON_PROJECT"
    CANCELLED_BY_US = "CANCELLED_BY_US"
    REJECTED = "REJECTED"
